config/routes.rb
Rails.application.routes.draw do
  post '/photos' => 'photos#create'

  devise_for :users, controllers: { registrations: 'registrations' }

  get 'profile' => 'users#show', as: 'profile'
  get 'dashboard' => 'dashboard#index', as: 'dashboard'

  resources :questions
  resources :games
  resources :subjects

  root to: "home#index"

  mount Ckeditor::Engine => '/ckeditor'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show]
      resources :questions, only: [:index, :show] do
        collection do
          get 'get_related'
        end
      end
      resources :subjects, only: [:index, :show]
      resources :school_grades, only: [:index, :show]
      resources :school_types, only: [:index, :show]
      resources :markers, only: [:index, :show]
      resources :games, except: [:new, :edit] do
        collection do
          get 'list_names'
          get 'by_pin/:pin' => 'games#by_pin'
        end

        member do
          post 'check_password'
        end
      end
    end
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  belongs_to :school_grade
  belongs_to :subject

  validates :question_text, :choice_a, :choice_b, :choice_c, :choice_d, :correct_answer, presence: true
  validates :difficulty_level, :school_grade_id, presence: { message: 'Please select one' }
  validate :duration_check

  def correct_answer_text
    [correct_answer.upcase, eval("choice_#{correct_answer.downcase}")].join('. ')
  end

  def formatted_duration
    duration.strftime("%H:%M:%S")
  end

  def duration_in_seconds
    hours, minutes, seconds = formatted_duration.split(":").map(&:to_i)
    (hours * 3600) + (minutes * 60) + seconds
  end

  private
  def duration_check
    errors.add(:duration, "The duration shouldn't be all zero") if formatted_duration.eql?("00:00:00")
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def get_related
    @questions = Question.where('subject_id = ? AND school_grade_id = ? AND difficulty_level = ? 
      AND (user_id = ? OR is_public IS TRUE)', params[:subject_id], params[:school_grade_id],
      params[:difficulty_level], params[:user_id])

    if @questions.empty?
      @questions = Question.where('subject_id = ? AND school_grade_id = ? 
        AND (user_id = ? OR is_public IS TRUE)', params[:subject_id], params[:school_grade_id],
        params[:user_id])
    end

    if @questions.empty?
      @questions = Question.where('user_id = ? OR is_public IS TRUE', params[:user_id])
    end

    render 'index'
  end

  private
  # Never trust parameters from the scary internet, only allow the white list through.
  def question_params
    params.require(:question).permit(:question_text, :choice_a, :choice_b, :choice_c, :choice_d,
      :choice_e, :correct_answer, :school_grade_id, :subject_id, :difficulty_level, :duration, :is_public)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /questions
  # GET /questions.json
  def index
    @questions = current_user.questions
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:question_text, :choice_a, :choice_b, :choice_c, :choice_d,
        :choice_e, :correct_answer, :school_grade_id, :subject_id, :difficulty_level, :duration, :is_public)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def set_choice(correct_answer, current_answer)
    if correct_answer && correct_answer.downcase.eql?(current_answer)
      'has-success'
    end
  end

  def set_difficulty_label(difficulty)
    label = case difficulty
              when 'Easy'
                "<h3 style=\"margin-top: 5px;\"><div class=\"label label-success\">#{difficulty}</div><h3>"
              when 'Medium'
                "<h3 style=\"margin-top: 5px;\"><div class=\"label label-info\">#{difficulty}</div><h3>"
              when 'Hard'
                "<h3 style=\"margin-top: 5px;\"><div class=\"label label-danger\">#{difficulty}</div><h3>"
            end

    label.html_safe
  end
end

app/views/questions/_form.html.slim
- content_for :bottom_javascripts do
  = javascript_include_tag 'chosen.jquery.min', :questions

= simple_form_for @question, html: { role: 'form' } do |f|
  .form-group
    = f.input :question_text, as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full'}, rows: 20 }, error_html: { class: 'label label-danger' }, required: false

  .form-group
    .input-group class="#{ set_choice(f.object.correct_answer, 'a') }"
      span.input-group-addon
        b A
      = f.input_field :choice_a, class: 'form-control input-lg choice-field'

  .form-group
    .input-group class="#{ set_choice(f.object.correct_answer, 'b') }"
      span.input-group-addon
        b B
      = f.input_field :choice_b, class: 'form-control input-lg choice-field'

  .form-group
    .input-group class="#{ set_choice(f.object.correct_answer, 'c') }"
      span.input-group-addon
        b C
      = f.input_field :choice_c, class: 'form-control input-lg choice-field'

  .form-group
    .input-group class="#{ set_choice(f.object.correct_answer, 'd') }"
      span.input-group-addon
        b D
      = f.input_field :choice_d, class: 'form-control input-lg choice-field'

  .form-group
    .input-group class="#{ set_choice(f.object.correct_answer, 'e') }"
      span.input-group-addon
        b E
      = f.input_field :choice_e, class: 'form-control input-lg choice-field', placeholder: 'Leave blank if you want to have four choices only'

  .form-group.hide
    = f.input :correct_answer, as: :radio_buttons, collection: ["A", "B", "C", "D", "E"], required: false

  .form-group
    label Correct answer: &nbsp;
    h3 style="margin-top: 5px;"
      #correct-answer-label.label.label-success
        - if f.object.correct_answer.blank?
          | Choose one above
        - else
          = f.object.correct_answer_text

  .form-group
    = f.input :school_grade_id, as: :select, collection: SchoolGrade.get_collection, input_html: { class: 'form-control selectpicker', data: { placeholder: '- Select grade -' } }, error_html: { class: 'label label-danger' }, required: false

  .form-group
    - if f.object.school_grade_id
      = f.input :subject_id, as: :select, collection: Subject.collection_by_grade_id(f.object.school_grade_id), input_html: { class: 'form-control selectpicker', data: { placeholder: '- Select subject -' } }, error_html: { class: 'label label-danger' }, required: false
    - else
      = f.input :subject_id, as: :select, collection: [], input_html: { class: 'form-control selectpicker', data: { placeholder: '- Select grade first -' }, disabled: true }, error_html: { class: 'label label-danger' }, required: false

  .form-group
    = f.input :difficulty_level, as: :select, collection: ["Easy", "Medium", "Hard"], input_html: { class: 'form-control selectpicker', data: { placeholder: '- Select difficulty -' } }, error_html: { class: 'label label-danger' }, required: false

  .form-group
    label Duration (HH:MM:SS)
    = f.input :duration, label: false, input_html: { class: 'input-lg' }, include_seconds: true, default: { hour: 0, minute: 0, second: 0 }, error: false
    - if f.error :duration
      .label.label-danger = f.error :duration 

  .form-group
    label Scope
    br
    .btn-group
      button type="button" data-is-public="true" class="btn btn-primary btn-scope #{'active' if f.object.is_public}" Public
      button type="button" data-is-public="false" class="btn btn-primary btn-scope #{'active' unless f.object.is_public}" Private
    = f.input :is_public, as: :radio_buttons, label: 'Scope', collection: [['public', true], ['private', false]], wrapper_html: { class: 'hide' }, required: false

  .form-group
    = f.submit "Save question", class: 'btn btn-info btn-lg'

app/views/questions/edit.html.slim
.container
  .panel.panel-default.panel-with-margin
    .panel-heading 
      h2 Edit Question
    .panel-body
      == render 'form'

app/views/questions/index.html.slim
.container
  .panel.panel-default.panel-with-margin
    .panel-heading
      h2 
        span.glyphicon.glyphicon-question-sign &nbsp;
        | Questions

    .panel-body
      - if @questions.empty?
        .alert.alert-warning role='warning'
          strong Oops! &nbsp;
          | you haven't created any questions right now,&nbsp;
          = link_to 'create a new one', new_question_path
      - else
        - @questions.each do |question|
          .panel.panel-primary
            .panel-heading
              h4 
                | Question ##{question.id}
            .panel-body
              .col-lg-10
                blockquote
                  strong Question:
                  p = truncate(question.question_text.html_safe, length: 240, omission: "... #{link_to 'more', question}", escape: false)
                  strong Correct answer:
                  h4
                    .label.label-success = question.correct_answer_text
              .col-lg-2
                .form-group
                  = link_to question, class: 'btn btn-info form-control' do
                    span.glyphicon.glyphicon-eye-open &nbsp;
                    | Show
                .form-group
                  = link_to edit_question_path(question), class: 'btn btn-primary form-control' do
                    span.glyphicon.glyphicon-edit &nbsp;
                    | Edit
                .form-group                
                  = link_to question, data: { :confirm => 'Are you sure?' }, :method => :delete, class: 'btn btn-danger form-control' do
                    span.glyphicon.glyphicon-remove &nbsp;
                    | Delete

        = link_to new_question_path, class: 'btn btn-default btn-lg' do
          span.glyphicon.glyphicon-plus &nbsp;
          | Add new

app/views/questions/new.html.slim
.container
  .panel.panel-default.panel-with-margin
    .panel-heading 
      h2 New Question

    .panel-body
      == render 'form'

app/views/questions/show.html.slim
.container
  .panel.panel-default.panel-with-margin
    .panel-heading
      h3 
        | Question ##{@question.id}
    .panel-body
      .panel.panel-info
        .panel-body
          p = @question.question_text.html_safe

      - ('a'..'e').each do |char|
        - unless eval("@question.choice_#{char}").blank?
          .form-group
            .input-group class="#{ 'has-success' if @question.correct_answer.downcase.eql?(char) }"
              span.input-group-addon
                b = char.upcase
              .form-control.input-lg = eval("@question.choice_#{char}")

      .form-group
        label CORRECT ANSWER
        h3 style="margin-top: 5px;"
          .label.label-success
            = @question.correct_answer_text

      .form-group
        label SCHOOL GRADE
        p = @question.school_grade.name

      .form-group
        label SUBJECT
        p = @question.subject.name

      .form-group
        label DIFFICULTY
        = set_difficulty_label(@question.difficulty_level)

      .form-group
        label DURATION
        p 
          = @question.formatted_duration
          | &nbsp; / 
          = pluralize(@question.duration_in_seconds, 'second')

      .form-group
        label SCOPE
        br
        .btn-group
          button type="button" data-is-public="true" class="btn btn-info btn-scope #{'active' if @question.is_public}" Public
          button type="button" data-is-public="false" class="btn btn-info btn-scope #{'active' unless @question.is_public}" Private

      hr

      = link_to edit_question_path(@question), class: 'btn btn-primary btn-lg' do
        span
          i.glyphicon.glyphicon-edit
        | &nbsp;
        | Edit

      | &nbsp;

      = link_to questions_path, class: 'btn btn-primary btn-lg' do
        span
          i.glyphicon.glyphicon-list
        | &nbsp;
        | Back