config/routes.rb
Rails.application.routes.draw do
  post '/photos' => 'photos#create'

  devise_for :users, controllers: { registrations: 'registrations' }

  get 'profile' => 'users#show', as: 'profile'
  get 'dashboard' => 'dashboard#index', as: 'dashboard'

  resources :questions
  resources :games
  resources :subjects

  root to: "home#index"

  mount Ckeditor::Engine => '/ckeditor'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show]
      resources :questions, only: [:index, :show] do
        collection do
          get 'get_related'
        end
      end
      resources :subjects, only: [:index, :show]
      resources :school_grades, only: [:index, :show]
      resources :school_types, only: [:index, :show]
      resources :markers, only: [:index, :show]
      resources :games, except: [:new, :edit] do
        collection do
          get 'list_names'
          get 'by_pin/:pin' => 'games#by_pin'
        end

        member do
          post 'check_password'
        end
      end
    end
  end

end

app/views/partials/_navbar.html.slim
#top-bar.nav.navbar.navbar-inverse.navbar-static-top role="navigation" 
  .container
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      button.navbar-toggle.collapsed data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "Smart Adventurer", root_path, class: 'navbar-brand navbar-title'
    /! Collect the nav links, forms, and other content for toggling

    - if user_signed_in?
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav
          li class="#{is_active?('home')}"
            = link_to root_path do
              span.glyphicon.glyphicon-home &nbsp;
              | Home
          li class="#{is_active?('dashboard')}"
            = link_to dashboard_path do
              span.glyphicon.glyphicon-dashboard &nbsp;
              | Dashboard
          li class="#{is_active?('questions')}"
            = link_to questions_path do
              span.glyphicon.glyphicon-question-sign &nbsp;
              | Questions
          li class="#{is_active?('games')}"
            = link_to games_path do
              span.glyphicon.glyphicon-globe &nbsp;
              | Games
        ul.nav.navbar-nav.navbar-right
          li.divider-vertical
          li.dropdown class="#{is_active?('users')}"
            = link_to "<span class=\"glyphicon glyphicon-user\"></span>&nbsp; Account <span class=\"caret\"></span>".html_safe, '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' }
            ul class="dropdown-menu" role="menu"
              li 
                = link_to 'My profile', profile_path
              li 
                = link_to 'Settings', '#'
              li class="divider"
              li 
                = link_to 'Sign out', destroy_user_session_path, method: :delete
    - else
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        ul.nav.navbar-nav
          li class="#{is_active?('home')}"
            = link_to root_path do
              span.glyphicon.glyphicon-home &nbsp;
              | Home
          li
            = link_to "#" do
              span.glyphicon.glyphicon-question-sign &nbsp;
              | How to
          li
            = link_to "#" do
              span.glyphicon.glyphicon-info-sign &nbsp;
              | About
          li
            = link_to "#" do
              span.glyphicon.glyphicon-earphone &nbsp;
              | Contact
        ul.nav.navbar-nav.navbar-right
          li
            form
              = link_to new_user_registration_path, class: 'btn btn-info navbar-btn' do
                | Sign up &nbsp;
                span.glyphicon.glyphicon-user
          li.divider-vertical
          li
            form
              = link_to new_user_session_path, class: 'btn btn-success navbar-btn' do
                | Sign in &nbsp;
                span.glyphicon.glyphicon-log-in