config/routes.rb
Rails.application.routes.draw do
  post '/photos' => 'photos#create'

  devise_for :users, controllers: { registrations: 'registrations' }

  get 'profile' => 'users#show', as: 'profile'
  get 'dashboard' => 'dashboard#index', as: 'dashboard'

  resources :questions
  resources :games
  resources :subjects

  root to: "home#index"

  mount Ckeditor::Engine => '/ckeditor'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show]
      resources :questions, only: [:index, :show] do
        collection do
          get 'get_related'
        end
      end
      resources :subjects, only: [:index, :show]
      resources :school_grades, only: [:index, :show]
      resources :school_types, only: [:index, :show]
      resources :markers, only: [:index, :show]
      resources :games, except: [:new, :edit] do
        collection do
          get 'list_names'
          get 'by_pin/:pin' => 'games#by_pin'
        end

        member do
          post 'check_password'
        end
      end
    end
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :school
  belongs_to :user
  has_many :markers, dependent: :destroy

  accepts_nested_attributes_for :markers, :reject_if => :all_blank, :allow_destroy => true

  before_create :generate_pin
  before_save :encrypt_password

  validates :name, :address, presence: true
  validates :game_type, presence: { message: 'please select game type' }
  validates :password, presence: true, if: Proc.new { |game| game.use_password && game.new_record? }
  validates_confirmation_of :password, if: Proc.new { |game| game.use_password && game.changed.include?("password") }
  validate :validate_markers

  def generate_pin
    self.pin = Time.now.strftime("%d%m%Y%H%M%S")
  end

  def validate_markers
    if markers.empty?
      errors.add(:markers, "You should put one start and finish marker, and at least two regular markers")
    else
      start_finish_markers = markers.group_by { |marker| ["start", "finish"].include? marker.marker_type }.values
      regular_markers = markers.group_by { |marker| !["start", "finish"].include?(marker.marker_type) }.values
      if !start_finish_markers.length.eql?(2) && !(regular_markers.length > 1)
        errors.add(:markers, "You should add one start and finish marker, and at least two regular markers")
      end
    end
  end

  private
  def encrypt_password
    self.password = if use_password
                      if !self.new_record? && self.changed.include?('password') && self.password.blank?
                        self.changes[:password].first
                      else
                        BCrypt::Password.create(password)
                      end
                    end
  end
end

app/controllers/api/v1/games_controller.rb
class Api::V1::GamesController < Api::V1::ApplicationController
  before_action :set_game, only: [:show, :update, :destroy, :check_password]

  def index
    @games = Game.all
  end

  def create
    @game = Game.new(game_params)

    if @game.save
      render 'show'
    else
      render json: @game.errors, status: :unprocessable_entity
    end
  end

  def update
    if @game.update(game_params)
      render 'show'
    else
      render json: @game.errors, status: :unprocessable_entity
    end
  end

  def show; end

  def destroy
    @game.destroy
    render json: { info: 'Game successfully deleted' }, status: :ok
  end

  def by_pin
    @game = Game.where(pin: params[:pin]).first
    render 'api/v1/games/show'
  end

  def check_password
    if @game && @game.use_password
      decrypted_password = BCrypt::Password.new(@game.password)

      if decrypted_password == params[:password]
        render 'api/v1/games/show'
      else
        render json: { error: 'Wrong password' }, status: :ok
      end
    else
      render 'api/v1/games/show'
    end
  end 

  def list_names
    @games = Game.select(:id, :name, :address, :pin)
  end

  private
  def set_game
    @game = Game.find(params[:id]) rescue nil
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def game_params
    params.require(:game).permit(:name, :pin, :address, :password, :password_confirmation, 
      :use_password, :game_type, markers_attributes: [:id, :marker_type, :latitude, :longitude, :_destroy])
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /games
  # GET /games.json
  def index
    @games = current_user.games
    @question_count = current_user.questions.count 
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = current_user.games.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def game_params
    params.require(:game).permit(:name, :pin, :address, :password, :password_confirmation, 
      :use_password, :game_type, markers_attributes: [:id, :marker_type, :latitude, :longitude, :_destroy])
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def marker_type_collection(game)
    marker_types = %w(gold question start finish)
    if game
      marker_types - game.markers.map(&:marker_type).select { |marker_type| ["start", "finish"].include? marker_type }
    else
      marker_types
    end
  end
end

app/views/games/_form.html.slim
- content_for :bottom_javascripts do
  = javascript_include_tag :games

= simple_form_for @game, html: { id: 'new-marker', role: 'form' } do |f|
  .form-group
    = f.input :name, input_html: { class: 'form-control input-lg' }, error_html: { class: 'label label-danger' }, required: false

  .form-group
    = f.input :address, input_html: { class: 'form-control input-lg', readonly: true }, error_html: { class: 'label label-danger' }, required: false

  .form-group
    = f.input :game_type, as: :select, collection: ["follow the route", "free running"], input_html: { class: 'form-control input-lg' }, prompt: '- Select type -', error_html: { class: 'label label-danger' }, required: false

  .form-group
    = f.input :use_password, as: :boolean, label: "&nbsp; use password".html_safe, required: false

  .password-container class="#{ 'hide' unless f.object.use_password }"
    .form-group
      = f.input :password, as: :password, input_html: { class: 'form-control input-lg' }, error_html: { class: 'label label-danger' }, placeholder: "#{f.object.new_record? ? 'Enter password' : 'Enter new password'}", required: false

    .form-group
      = f.input :password_confirmation, as: :password, input_html: { class: 'form-control input-lg' }, error_html: { class: 'label label-danger' }, placeholder: "#{f.object.new_record? ? 'Confirm password' : 'Confirm new password'}", required: false

  .form-group
    #map.game-maps
    - if f.error :markers
      .alert.alert-danger
        p 
          strong 
            | Warning! &nbsp;
          = f.error :markers
  .hide
    h3 markers
    #markers
      = f.simple_fields_for :markers do |marker|
        = render 'marker_fields', :f => marker
      .links
        = link_to_add_association 'add task', f, :markers

  .form-group
    = f.submit "Save game", class: 'btn btn-info btn-lg'

#infowindow-content.hide
  .infowindow-content-container id="infowindow-{{marker-field-id}}"
    .panel.panel-default style="background: #fff; width: 300px"
      .panel-heading
        h3.panel-title
          | {{title}}
      .panel-body
        p.marker-description 
          | this marker indicating location of a {{type}}
        p
          .form-group
            = simple_form_for :edit_marker, html: { id: 'editMarkerForm', role: 'form' } do |f|
              = f.input :marker_type, collection: marker_type_collection(f.object), prompt: '- Select type -', input_html: { class: 'existing-marker-marker-type form-control input' }, label: false
          = link_to 'Save', 'javascript:void(0);', class: 'btn-save-marker btn btn-info'
          | &nbsp;
          = link_to 'Remove', 'javascript:void(0);', class: 'btn-remove-marker btn btn-danger'

#marker-modal.modal
  .modal-dialog
    .modal-content
      .modal-header
        h4.modal-title New Marker Dialog
      .modal-body
        = simple_form_for :new_marker, html: { id: 'newMarkerForm', role: 'form' } do |f|
          .form-group
            = f.input :marker_type, collection: marker_type_collection(f.object), prompt: '- Select type -', input_html: { class: 'marker-field form-control input-md', data: { marker_field_id: "" } }
          .form-group
            = f.input :use_address, label: 'use address manually', input_html: { class: 'marker-field' }, as: :boolean, wrapper: :checkbox, data: { marker_field_id: "" }
          .form-group#address-container.hide
            = f.input :address, input_html: { class: 'marker-field form-control input-md skip-validate', data: { marker_field_id: "" } }
          .hide
            .form-group
              = f.input :address_latitude, input_html: { class: 'marker-field form-control input-md skip-validate', data: { marker_field_id: "" } }
            .form-group
              = f.input :address_longitude, input_html: { class: 'marker-field form-control input-md skip-validate', data: { marker_field_id: "" } }
            .form-group
              = f.input :latitude, input_html: { class: 'marker-field form-control input-md', data: { marker_field_id: "" } }
            .form-group
              = f.input :longitude, input_html: { class: 'marker-field form-control input-md', data: { marker_field_id: "" } }
          .form-group
            = f.submit "Put marker", id: 'btn-put-marker', class: 'btn btn-info btn-lg btn-block', data: { marker_field_id: "" }
            = link_to "Cancel", "javascript:void(0);", id: "btn-cancel", class: 'btn btn-danger btn-lg btn-block', data: { marker_field_id: "" }

      .modal-footer
        | &nbsp;

app/views/games/_marker_fields.html.slim
.marker-fields.nested-fields.col-lg-12
  .col-lg-2
    = f.input :marker_type, input_html: { class: 'form-control input-sm marker-type' }
  .col-lg-2
    = f.input :latitude, input_html: { class: 'form-control input-sm' }
  .col-lg-2
    = f.input :longitude, input_html: { class: 'form-control input-sm' }
  .col-lg-2
    = link_to_remove_association "remove marker", f

app/views/games/edit.html.slim
.container
  .panel.panel-default.panel-with-margin
    .panel-heading
      h3 Edit game
    .panel-body
      == render 'form'

app/views/games/index.html.slim
- content_for :bottom_javascripts do
  = javascript_include_tag :games

.container
  .panel.panel-default.panel-with-margin
    .panel-heading
      h2 
        span.glyphicon.glyphicon-globe &nbsp;
        | Games
    .panel-body
      - if @question_count.zero?
        .alert.alert-warning role='warning'
          strong Oops! &nbsp;
          | you haven't created any questions right now, please create question before create a game.&nbsp;
          = link_to 'create a new one', new_question_path
      - else
        - if @games.empty?
          .alert.alert-warning role='warning'
            strong Oops! &nbsp;
            | you haven't created any games right now,&nbsp;
            = link_to 'create a new one', new_game_path
        - else
          - @games.each do |game|
            .panel.panel-primary
              .panel-heading 
                h3 = game.name
              .panel-body
                table.table
                  tr
                    td width="100"
                      b PIN
                    td = game.pin
                  tr
                    td
                      b AREA
                    td = ['Near', game.address].join(' ')
                  tr
                    td 
                      b TYPE
                    td = game.game_type.upcase
                  tr
                    td
                      b PASSWORD
                    td
                      - if game.use_password?
                        .label.label-success YES
                      - else
                        .label.label-default NO

                = content_tag "div", "", id: "marker-data-#{game.id}", class: "marker-data", data: { marker_data: game.markers }

                .map-container style="position: relative"
                  = content_tag "div", "", id: "map-#{game.id}", class: "game-maps"
                  .buttons-container.col-lg-6 style="position: absolute; bottom: 20px; right: 0px;"
                    .col-lg-4 
                      = link_to game, class: 'btn btn-info form-control' do
                        span.glyphicon.glyphicon-eye-open &nbsp;
                        | Show
                    .col-lg-4 
                      = link_to edit_game_path(game), class: 'btn btn-primary form-control' do
                        span.glyphicon.glyphicon-edit &nbsp;
                        | Edit
                    .col-lg-4 
                      = link_to game, data: { :confirm => 'Are you sure?' }, method: :delete, class: 'btn btn-danger form-control' do
                        span.glyphicon.glyphicon-remove &nbsp;
                        | Delete

          = link_to new_game_path, class: 'btn btn-default btn-lg' do
            span.glyphicon.glyphicon-plus &nbsp;
            | Add new

app/views/games/new.html.slim
.container
  .panel.panel-default.panel-with-margin
    .panel-heading
      h3 New game
    .panel-body
      == render 'form'

app/views/games/show.html.slim
- content_for :bottom_javascripts do
  = javascript_include_tag :games

.container
  .panel.panel-info.panel-with-margin
    .panel-heading
      h3 = @game.name
    .panel-body
      form role="form"
        .form-group
          blockquote
            p = @game.name
            footer NAME

        .form-group
          blockquote
            p = @game.pin
            footer PIN

        .form-group
          blockquote
            p = ['Near', @game.address].join(' ')
            footer AREA

        .form-group
          blockquote
            p = @game.game_type
            footer GAME TYPE

        .form-group
          blockquote
            p
              - if @game.use_password?
                .label.label-success YES
              - else
                .label.label-default NO
            footer USE PASSWORD

        br

        .form-group
          = content_tag "div", "", id: "marker-data-#{@game.id}", class: "marker-data", data: { marker_data: @game.markers }
          .map-container
            = content_tag "div", "", id: "map-#{@game.id}", class: "game-maps"

        .form-group
          = link_to edit_game_path(@game), class: 'btn btn-primary btn-lg' do
            span
              i.glyphicon.glyphicon-edit
            | &nbsp;
            | Edit
          | &nbsp;
          = link_to games_path, class: 'btn btn-primary btn-lg' do
            span
              i.glyphicon.glyphicon-list
            | &nbsp;
            | Back