config/routes.rb
Rails.application.routes.draw do
  post '/photos' => 'photos#create'

  devise_for :users, controllers: { registrations: 'registrations' }

  get 'profile' => 'users#show', as: 'profile'
  get 'dashboard' => 'dashboard#index', as: 'dashboard'

  resources :questions
  resources :games
  resources :subjects

  root to: "home#index"

  mount Ckeditor::Engine => '/ckeditor'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show]
      resources :questions, only: [:index, :show] do
        collection do
          get 'get_related'
        end
      end
      resources :subjects, only: [:index, :show]
      resources :school_grades, only: [:index, :show]
      resources :school_types, only: [:index, :show]
      resources :markers, only: [:index, :show]
      resources :games, except: [:new, :edit] do
        collection do
          get 'list_names'
          get 'by_pin/:pin' => 'games#by_pin'
        end

        member do
          post 'check_password'
        end
      end
    end
  end

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :school_grade

  def self.all_by_grade_id(grade_id)
    self.where(school_grade_id: grade_id)
  end

  def self.collection_by_grade_id(grade_id)
    self.all_by_grade_id(grade_id).map { |subject| [subject.name, subject.id] }
  end
end

app/controllers/api/v1/subjects_controller.rb
class Api::V1::SubjectsController < ApplicationController
  def index
    @subjects = Subject.all
  end

  def show
    @subject = Subject.find(params[:id])
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    if params[:grade_id]
      @subjects = Subject.all_by_grade_id(params[:grade_id])
      render json: @subjects
    else
      @subjects = Subject.all
    end
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params[:subject]
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.slim
= form_for @subject do |f|
  - if @subject.errors.any?
    #error_explanation
      h2 = "#{pluralize(@subject.errors.count, "error")} prohibited this subject from being saved:"
      ul
        - @subject.errors.full_messages.each do |message|
          li = message

  .actions = f.submit 'Save'

app/views/subjects/edit.html.slim
h1 Editing subject

== render 'form'

= link_to 'Show', @subject
'|
= link_to 'Back', subjects_path

app/views/subjects/index.html.slim
h1 Listing subjects

table
  thead
    tr
      th
      th
      th

  tbody
    - @subjects.each do |subject|
      tr
        td = link_to 'Show', subject
        td = link_to 'Edit', edit_subject_path(subject)
        td = link_to 'Destroy', subject, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Subject', new_subject_path

app/views/subjects/new.html.slim
h1 New subject

== render 'form'

= link_to 'Back', subjects_path

app/views/subjects/show.html.slim
p#notice = notice


= link_to 'Edit', edit_subject_path(@subject)
'|
= link_to 'Back', subjects_path